import React, { useState } from 'react'



export default function TextForm(props) {
    const handleUpClick = () => {
        // console.log("UpperCase was clicked")
        let newText = text.toUpperCase();
        // setText("You have clicked on handleUpClick")
        setText(newText)
    }
    const handleLoClick = () => {
        // console.log("UpperCase was clicked")
        let newText = text.toLowerCase();
        // setText("You have clicked on handleUpClick")
        setText(newText)
    }
    const handleOnChange = (event) => {
        // console.log("OnChange was clicked")
        setText(event.target.value)
    }
    const [text, setText] = useState('Enter Text Here');
    return (
        <>
            <div className="container">
                <h1>{props.heading}</h1>
                <div className="mb-3">
                    <label htmlFor="myBox" className="form-label"></label>
                    <textarea className="form-control" value={text} onChange={handleOnChange} id="myBox" rows="8"></textarea>
                </div>
                <button className="btn btn-primary mx-2" onClick={handleUpClick}> Convert to UpperCase</button>
                <button className="btn btn-primary mx-2" onClick={handleLoClick}> Convert to LowerCase</button>
            </div>
            <div className="container my-3">
                <h1>Your Text Summary</h1>
                <p>{text.split(" ").length} words and {text.length} characters</p>
                {/* below data is being generated by the data provided by "https://scholarwithin.com/average-reading-speed" for adults */}
                <p>{0.003 * text.split(" ").length} minutes read</p>
                <h3>Preview</h3>
                <p>{text}</p>
            </div>
        </>

    )
}
